In [3]:
# Q1. Create a Pandas Series from a list of integers.
# *Hint:** Use `pd.Series([...])`. The default index starts from 0.

import pandas as pd

S = pd.Series([10,20,30,40,50])
print(S)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# Q2. Create a Series from a dictionary with custom index.
# Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

data = {'a': 10, 'b': 20, 'c': 30 }
S = pd.Series(data)
print(S)

a    10
b    20
c    30
dtype: int64

In [5]:
# Q3. Access elements using index labels.
# Hint:** Use `s["label"]` for a single value, 
# `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. 
# Label slices are **inclusive** on both ends.

s = pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd'])
print(s['b'])                   # Single element
print(s[['a','b']])             # Multiple element
print(s['a':'c'])               # Range

20
a    10
b    20
dtype: int64
a    10
b    20
c    30
dtype: int64

In [6]:
# Q4. Perform arithmetic operations on a Series.
# Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` 
# directly on the Series. Operations are **element-wise** and **index-aligned**.

s = pd.Series([10,20,30,40])

print(s + 5)
print(s - 5)
print(s * 5)
print(s / 5)
print(s // 5)
print(s ** 5)

0    15
1    25
2    35
3    45
dtype: int64
0     5
1    15
2    25
3    35
dtype: int64
0     50
1    100
2    150
3    200
dtype: int64
0    2.0
1    4.0
2    6.0
3    8.0
dtype: float64
0    2
1    4
2    6
3    8
dtype: int64
0       100000
1      3200000
2     24300000
3    102400000
dtype: int64

In [7]:
# Q5. Find mean, min, max of a Series.
# Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

s = pd.Series([10, 20, 30, 40, 50])

print('Mean :', s.mean())
print('Min :', s.min())
print('Max :', s.max())
print('Sum :', s.sum())
print('Median :', s.median())
print('Std :', s.std())

Mean : 30.0
Min : 10
Max : 50
Sum : 150
Median : 30.0
Std : 15.811388300841896

In [8]:
# Q6. Apply conditional filtering on a Series.
# Hint:** Use a boolean mask: `s[s > 50]`. 
# You can also chain conditions with `&` and `|`.

s = pd.Series([10, 20, 30, 40, 50, 60, 70, 80])

print(s [s > 30]) 
print(s [s % 2 == 0])
print(s [(s > 20) & (s < 60)])
print(s[(s > 30) | (s < 50)])

3    40
4    50
5    60
6    70
7    80
dtype: int64
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64
2    30
3    40
4    50
dtype: int64
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [9]:
# Q7. Replace values in a Series.
# Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `
# {old: new}` to replace multiple values at once.

s = pd.Series([10, 20, 30, 20, 10, 50])

print(s.replace(10, 99))              # Single Replace
print(s.replace({10 : 99, 20 : 88}))  # Multiple replace using dict
print(s.replace([10, 20], [99, 88]))  # Multiple replace using list

0    99
1    20
2    30
3    20
4    99
5    50
dtype: int64
0    99
1    88
2    30
3    88
4    99
5    50
dtype: int64
0    99
1    88
2    30
3    88
4    99
5    50
dtype: int64

In [10]:
# Q8. Convert Series data type.
# Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

s = pd.Series(['10', '20', '30', '40', '50'])

print(s.astype(int))
print(s.astype(float))
print(s.astype('category'))

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64
0    10
1    20
2    30
3    40
4    50
dtype: category
Categories (5, object): ['10', '20', '30', '40', '50']

In [11]:
# Q9. Check for null values in Series.
# Hint:** Use `.isnull()` (returns boolean Series) or `.
# isnull().sum()` for a count.

import pandas as pd
import numpy as np

s = pd.Series([10, 20, 30, np.nan, 40, 50, None])

print(s.isnull())         # Boolean mask = True where null
print(s.isnull().sum())   # Count of null values
print(s.notnull())        # True where Not Null

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
2
0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [12]:
# Q10. Fill missing values in Series.
# Hint:** Use `.fillna(value)` for constant, `
# .fillna(s.mean())` for mean, `.ffill()` for forward fill, `
# .bfill()` for backward fill.

s = pd.Series([10, np.nan, 30, 40, np.nan, 60, 70])

print(s.fillna(1))          # Fill with given number
print(s.fillna(s.mean()))   # Fill with mean
print(s.ffill())            # Forward Fill - Copy previous value
print(s.bfill())            # Backward Fill - Copy next value

0    10.0
1     1.0
2    30.0
3    40.0
4     1.0
5    60.0
6    70.0
dtype: float64
0    10.0
1    42.0
2    30.0
3    40.0
4    42.0
5    60.0
6    70.0
dtype: float64
0    10.0
1    10.0
2    30.0
3    40.0
4    40.0
5    60.0
6    70.0
dtype: float64
0    10.0
1    30.0
2    30.0
3    40.0
4    60.0
5    60.0
6    70.0
dtype: float64

In [13]:
# Q11. Create DataFrame from a list.
# Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. 
# Each inner list becomes one row.

data = [['Snehal', 23, 'HR'],
        ['Komal', 24, 'Finance'],
        ['SK', 25, 'CS']]
df = pd.DataFrame(data, columns= ['Name', 'Age', 'Department'])
print(df)

     Name  Age Department
0  Snehal   23         HR
1   Komal   24    Finance
2      SK   25         CS

In [14]:
# Q12. Create DataFrame from a dictionary.
# Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

data = {
    'Name' : ['Snehal', 23, 'HR'],
    'Age'  : ['Komal', 24, 'Finance'],
    'Department'   : ['SK', 25, 'CS']
}
df = pd.DataFrame(data)
print(df)

     Name      Age Department
0  Snehal    Komal         SK
1      23       24         25
2      HR  Finance         CS

In [15]:
# Q13. Create DataFrame from list of dictionaries.
# Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

data = [
    {'Name': 'Alice', 'Age': 25, 'Department': 'HR'},
    {'Name': 'Bob',   'Age': 30, 'Department': 'IT'},
    {'Name': 'Carol', 'Age': 28}  
]
df = pd.DataFrame(data)
print(df)

    Name  Age Department
0  Alice   25         HR
1    Bob   30         IT
2  Carol   28        NaN

In [16]:
# Q14. Display DataFrame structure (shape, columns, dtypes).
# Hint: Use `df.shape`,`df.columns`,`df.dtypes`, `df.info()`,and `df.describe()`.

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())

(3, 3)
Index(['Name', 'Age', 'Department'], dtype='object')
Name          object
Age            int64
Department    object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Age         3 non-null      int64
 2   Department  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
             Age
count   3.000000
mean   27.666667
std     2.516611
min    25.000000
25%    26.500000
50%    28.000000
75%    29.000000
max    30.000000

In [17]:
# Q15. Select single column from DataFrame.
# Hint:** Use `df["col_name"]` — this returns a **Series**.
#  You can also use `df.col_name` (dot notation).

data = {
    'Name'      : ['snheal', 'Komal', 'SK'],
    'Age'       : [25, 30, 28],
    'Department': ['HR', 'IT', 'Finance']
}
df = pd.DataFrame(data)

print(df['Name'])        # returns series
print(df.Age)            # dot notaion
print(type(df['Name']))  # confirmation

0    snheal
1     Komal
2        SK
Name: Name, dtype: object
0    25
1    30
2    28
Name: Age, dtype: int64
<class 'pandas.core.series.Series'>

In [18]:

# Q16. Select multiple columns.
# Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets 
# — this returns a **DataFrame**.

data = {
    'Name'      : ['snheal', 'Komal', 'SK'],
    'Age'       : [25, 30, 28],
    'Department': ['HR', 'IT', 'Finance']
}
df = pd.DataFrame(data)

print(df[['Name', 'Age']])                # select only 2 columns
print(df[['Name','Department']])          # different order = recorder columns
print(df[['Name', 'Age', 'Department']])  # select 3 columns

     Name  Age
0  snheal   25
1   Komal   30
2      SK   28
     Name Department
0  snheal         HR
1   Komal         IT
2      SK    Finance
     Name  Age Department
0  snheal   25         HR
1   Komal   30         IT
2      SK   28    Finance

In [19]:
# Q17. Add new column with scalar value.
# Hint:df["new_col"]=10` — the scalar is *broadcast* to all rows automatically.

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}

df = pd.DataFrame(data)

df['Tax_rate'] = 0.10
df['Bonus'] = df['Salary'] * 0.10 
print(df)

     Name  Age  Salary Department  Tax_rate    Bonus
0  Snehal   23  120000         Hr       0.1  12000.0
1   Komal   24  230000         IT       0.1  23000.0
2      SK   25  340000    Finance       0.1  34000.0

In [20]:
# Q18. Add column using Series.
# Hint:** `df["new_col"] = pd.Series([...])`. 
# The Series index must align with the DataFrame index.

data = {
    'Name'      : ['snheal', 'Komal', 'SK'],
    'Age'       : [25, 30, 28],
    'Salary'     :[120000, 230000, 340000]
}
df = pd.DataFrame(data, index=[101, 102, 103])
print(df)

       Name  Age  Salary
101  snheal   25  120000
102   Komal   30  230000
103      SK   28  340000

In [21]:
# Q19. Rename columns using `rename()`.
# Hint:** Use `df.rename(columns={"old": "new"})`. 
# Add `inplace=True` to modify in-place.

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}
df = pd.DataFrame(data)

print(df.rename(columns={'Name' : 'Employee'}, inplace=True))
print(df)

None
  Employee  Age  Salary Department
0   Snehal   23  120000         Hr
1    Komal   24  230000         IT
2       SK   25  340000    Finance

In [22]:
# Q20. Rename multiple columns.
# Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}
df = pd.DataFrame(data)
df.rename(columns={'Name':'Employee','salary':'Income', 'Age' : 'Years'})
print(df)

     Name  Age  Salary Department
0  Snehal   23  120000         Hr
1   Komal   24  230000         IT
2      SK   25  340000    Finance


## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

In [23]:
# Q21. Select rows using `loc`.
# Hint:** `df.loc[label]` for a single row, 
# `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}
df = pd.DataFrame(data)
#
print(df.loc[0])
print(df.loc[1 : 3])
print(df.loc[1 : 3, ['Name', 'Salary']])

Name          Snehal
Age               23
Salary        120000
Department        Hr
Name: 0, dtype: object
    Name  Age  Salary Department
1  Komal   24  230000         IT
2     SK   25  340000    Finance
    Name  Salary
1  Komal  230000
2     SK  340000

In [24]:
# Q22. Select rows using `iloc`.
# Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. 
# **Exclusive on the end** (Python-style).

data = {
    'Name'       :['Snehal', 'Komal', 'SK'],
    'Age'        :[23, 24, 25],
    'Salary'     :[120000, 230000, 340000],
    'Department' :['Hr','IT','Finance']
}
df = pd.DataFrame(data)

print(df.iloc[0])       # First row
print(df.iloc[1:4])     # rows at position 1,2,3
print(df.iloc[0,1])     # row 0, column 1

Name          Snehal
Age               23
Salary        120000
Department        Hr
Name: 0, dtype: object
    Name  Age  Salary Department
1  Komal   24  230000         IT
2     SK   25  340000    Finance
23

In [25]:
# Q23. Access specific row and column.
# Hint:** `df.loc[row_label, "col_name"]` or `\
# df.iloc[row_pos, col_pos]` for a single cell.

data = {
    'Name'      : ['Snehal', 'Komal', 'SK', 'Raj', 'Priya'],
    'Age'       : [23, 24, 25, 26, 27],
    'Salary'    : [120000, 230000, 340000, 450000, 560000],
    'Department': ['HR', 'IT', 'Finance', 'HR', 'IT']
}

df = pd.DataFrame(data)

print(df.loc[0, 'Name'])    # label - based  
print(df.iloc[0,1])          # position - based

Snehal
23

In [26]:
# Q24. Select subset using multiple rows & columns.
# Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

print(df.loc[[0, 2], ['Name', 'Salary']])
print(df.iloc[[0.2], [0,2]])

     Name  Salary
0  Snehal  120000
2      SK  340000
     Name  Salary
0  Snehal  120000

In [27]:
# Q25. Apply conditional filtering using `loc`.
# Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

print(df.loc[df['Salary'] > 230000, ['Name','Salary']])

    Name  Salary
2     SK  340000
3    Raj  450000
4  Priya  560000

In [28]:
# Q26. Slice rows using index range.
# Hint:** Use `df.iloc[start:end]` for position-based slicing or 
# `df.loc[label1:label2]` for label-based slicing.

print(df.loc[2:3])
print(df.loc[1:5])

  Name  Age  Salary Department
2   SK   25  340000    Finance
3  Raj   26  450000         HR
    Name  Age  Salary Department
1  Komal   24  230000         IT
2     SK   25  340000    Finance
3    Raj   26  450000         HR
4  Priya   27  560000         IT

In [29]:
# Q27. Slice columns using labels.
# Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

print(df.loc[:,'Age' :'Salary'])

   Age  Salary
0   23  120000
1   24  230000
2   25  340000
3   26  450000
4   27  560000

In [30]:
# Q28. Slice columns using position.
# Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

print(df.iloc[:, 1:4])

   Age  Salary Department
0   23  120000         HR
1   24  230000         IT
2   25  340000    Finance
3   26  450000         HR
4   27  560000         IT

In [31]:
# Q29. Perform combined row & column slicing.
# Hint:** `df.loc[row_condition, ["col1","col2"]]` or `
# df.iloc[0:5, [0, 2, 4]]`.

print(df.loc[df['Age'] > 24, ['Name','Department']]) # condition + columns
print(df.iloc[0:3, [0,2]])

    Name Department
2     SK    Finance
3    Raj         HR
4  Priya         IT
     Name  Salary
0  Snehal  120000
1   Komal  230000
2      SK  340000

In [32]:
# Q30. Set a column as index.
# Hint:** Use `df.set_index("col_name")`.
#  Add `inplace=True` to modify without reassigning.

df.set_index('Name', inplace=True)
print(df)

        Age  Salary Department
Name
Snehal   23  120000         HR
Komal    24  230000         IT
SK       25  340000    Finance
Raj      26  450000         HR
Priya    27  560000         IT

In [33]:
# Q31. Create hierarchical index (MultiIndex).
# Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

data = {
    'Name'      : ['Snehal', 'Komal', 'SK', 'Raj', 'Priya'],
    'Age'       : [23, 24, 25, 26, 27],
    'Salary'    : [120000, 230000, 340000, 450000, 560000],
    'Department': ['HR', 'IT', 'Finance', 'HR', 'IT']
}

df = pd.DataFrame(data)

df_multi = df.set_index(['Department', 'Name'])
print(df_multi)

                   Age  Salary
Department Name
HR         Snehal   23  120000
IT         Komal    24  230000
Finance    SK       25  340000
HR         Raj      26  450000
IT         Priya    27  560000

In [34]:
# Q32. Reset index.
# Hint:** `df.reset_index()` — moves the current index back to a column.
#  Use `inplace=True` to modify in-place.


df.set_index('Name', inplace=True)
print("Before Reset:")
print(df)

df.reset_index(inplace=True)
print("\nAfter Reset:")
print(df)

Before Reset:
        Age  Salary Department
Name
Snehal   23  120000         HR
Komal    24  230000         IT
SK       25  340000    Finance
Raj      26  450000         HR
Priya    27  560000         IT

After Reset:
     Name  Age  Salary Department
0  Snehal   23  120000         HR
1   Komal   24  230000         IT
2      SK   25  340000    Finance
3     Raj   26  450000         HR
4   Priya   27  560000         IT

In [35]:
# Q33. Reset multi-index.
# Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.
# reset_index() converts all levels of a MultiIndex back into normal columns.


import pandas as pd

data = {
    'Name': ['Snehal', 'Komal', 'SK'],
    'Department': ['HR', 'IT', 'Finance'],
    'Salary': [120000, 230000, 340000]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Name'])
print(df)

df.reset_index(inplace=True)
print(df)

                   Salary
Department Name
HR         Snehal  120000
IT         Komal   230000
Finance    SK      340000
  Department    Name  Salary
0         HR  Snehal  120000
1         IT   Komal  230000
2    Finance      SK  340000

In [36]:
# Q34. Convert index to column.
# Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.
# reset_index() converts all levels of a MultiIndex back into normal columns.

import pandas as pd

data = {
    'Name': ['Snehal', 'Komal', 'SK'],
    'Salary': [120000, 230000, 340000]
}

df = pd.DataFrame(data)

df.set_index('Name', inplace=True)
print(df)

df.reset_index(inplace=True)
print(df)

        Salary
Name
Snehal  120000
Komal   230000
SK      340000
     Name  Salary
0  Snehal  120000
1   Komal  230000
2      SK  340000

In [37]:
# Q35. Use drop option in `reset_index`.
# Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.
# drop=True discards the old index and creates a fresh default integer index (0, 1, 2, ...).
data = {
    'Name': ['Snehal', 'Komal', 'SK'],
    'Salary': [120000, 230000, 340000]
}

df = pd.DataFrame(data)

df.set_index('Name', inplace=True)
print(df)

df.reset_index(drop=True)

        Salary
Name
Snehal  120000
Komal   230000
SK      340000

   Salary
0  120000
1  230000
2  340000

In [38]:
# Q36. Perform label-based indexing.
# Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

import pandas as pd

df = pd.DataFrame({
    'Age': [22, 25, 30]
}, index=['Snehal', 'Komal', 'Sk'])

print(df.loc['Komal'])

Age    25
Name: Komal, dtype: int64

In [39]:
# Q37. Perform position-based indexing.
# Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

print(df.iloc[0])

Age    22
Name: Snehal, dtype: int64

In [40]:
# Q38. Access first N rows.
# Hint:** `df.head(N)` — default N is 5.

data = {
    'Name': ['Snehal', 'Komal', 'SK', 'priya', 'Sheela'],
    'Age' : [20, 15, 23, 57, 32]
}
df = pd.DataFrame(data)
print(df.head(2))

     Name  Age
0  Snehal   20
1   Komal   15

In [42]:
# Q39. Access last N rows.
# Hint:** `df.tail(N)` — default N is 5.

print(df.tail(2))   #Last 2 rows

     Name  Age
3   priya   57
4  Sheela   32

In [43]:
# Q40. Extract random sample from DataFrame.
# Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

print(df.sample(n=3))  # random 3 rows

     Name  Age
3   priya   57
4  Sheela   32
0  Snehal   20

## 🔹 Section 3: Data Cleaning (Q41–Q60)

In [44]:
# Q41. Detect missing values using `isnull()`.
# Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.
# how many missing values are present in each column
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Snehal', 'Komal', np.nan],
    'Age': [22, np.nan, 30]
})

print(df.isnull())

    Name    Age
0  False  False
1  False   True
2   True  False

In [45]:
# Q42. Drop missing values using `dropna()`.
# Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.
# dropna() removes rows or columns containing missing values

print(df.dropna())

     Name   Age
0  Snehal  22.0

In [46]:
# Q43. Fill missing values with a constant.
# Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.
# fillna() preserves all records while handling missing values.

df.fillna(0)

     Name   Age
0  Snehal  22.0
1   Komal   0.0
2       0  30.0

In [47]:
# Q44. Fill missing values using mean/median.
# Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.
# mean :- Because extreme values affect the mean significantly, while the median remains stable.
df = pd.DataFrame({
    'Age': [20, 25, np.nan, 35]
})

df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

         Age
0  20.000000
1  25.000000
2  26.666667
3  35.000000

In [48]:
# Q45. Use forward fill and backward fill.
# Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.
# ffill() uses previous values, while bfill() uses next values to fill missing data.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Sales': [100, np.nan, np.nan, 200, 300]
})

print(df)

   Sales
0  100.0
1    NaN
2    NaN
3  200.0
4  300.0

In [49]:
# Q46. Convert data type using `astype()`.
# Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

import pandas as pd

df = pd.DataFrame({
    'Age': ['20', '25', '30']
})

df['Age'] = df['Age'].astype(int)
print(df.dtypes)

Age    int64
dtype: object

In [50]:
# Q47. Clean string column using `.str.lower()`.
# Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

import pandas as pd

df = pd.DataFrame({
    'Name': ['SNEHAL', 'KoMaL', 'SK']
})

df['Name'] = df['Name'].str.lower()
print(df)

     Name
0  snehal
1   komal
2      sk

In [51]:
# Q48. Trim whitespace in strings.
# Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.
# strip() removes unwanted spaces.

df['Name'] = df['Name'].str.strip()
print(df)

     Name
0  snehal
1   komal
2      sk

In [52]:
# Q49. Replace substring in column.
# Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

df = pd.DataFrame({
    'City': ['Bombay', 'Bombay', 'Delhi']
})

df['City'] = df['City'].str.replace('Bombay', 'Mumbai')
print(df)

     City
0  Mumbai
1  Mumbai
2   Delhi

In [53]:
# Q50. Extract part of string using `.str`.
# Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

df = pd.DataFrame({
    'Email': ['john@gmail.com',
              'alice@yahoo.com']
})

df['Domain'] = df['Email'].str.split('@').str[1]
print(df)

             Email     Domain
0   john@gmail.com  gmail.com
1  alice@yahoo.com  yahoo.com

In [54]:
# Q51. Detect duplicate rows.
# Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

import pandas as pd

df = pd.DataFrame({
    'Name': ['snehal', 'Komal', 'Sk', 'priya'],
    'Age': [25, 30, 25, 40]
})

print(df.duplicated())

0    False
1    False
2    False
3    False
dtype: bool

In [55]:
# Q52. Remove duplicates using `drop_duplicates()`.
# Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.
# drop_duplicates() function removes repeated records and keeps only unique rows.

df = df.drop_duplicates()
print(df)

     Name  Age
0  snehal   25
1   Komal   30
2      Sk   25
3   priya   40

In [56]:

# Q53. Rename row labels. : method updates only the specified label.
# Hint:** `df.rename(index={old_label: new_label})`.

df = pd.DataFrame({
    'Name': ['snehal', 'Komal', 'Sk', 'priya'],
    'Age': [25, 30, 25, 40]}, index=['A', 'B', 'C', 'D'])

df = df.rename(index={'A': 'Student1'})
print(df)

            Name  Age
Student1  snehal   25
B          Komal   30
C             Sk   25
D          priya   40

In [57]:
# Q54. Handle inconsistent data.
# Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.
# .str.strip() removes leading and trailing spaces from each value. 
# Then .str.lower() converts all characters to lowercase

df['Name'] = df['Name'].str.strip().str.lower()
print(df)

            Name  Age
Student1  snehal   25
B          komal   30
C             sk   25
D          priya   40

In [58]:
# Q55. Replace values in DataFrame.
# Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

df = df.replace('sk', 'Shital')
print(df)

            Name  Age
Student1  snehal   25
B          komal   30
C         Shital   25
D          priya   40

In [59]:
# Q56. Detect outliers in a column.
# Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1.
#  Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`.
#  Alternatively use Z-score: `|z| > 3`.

df = pd.DataFrame({
    'Salary': [30000, 35000, 40000, 45000, 50000, 60000, 500000]})

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower_value = Q1 - 1.5 * IQR
upper_value = Q3 + 1.5 * IQR

outliers = df [
    (df['Salary'] < lower_value) |
    (df['Salary'] > upper_value)]
print(outliers)

   Salary
6  500000

In [60]:
# Q57. Handle outliers using clipping.
# Hint:** `df["col"].clip(lower=lo, upper=hi)` 
# replaces values outside the bounds with the boundary values.

df['Salary'] = df['Salary'].clip(
    lower=30000,
    upper=100000)
print(df)

   Salary
0   30000
1   35000
2   40000
3   45000
4   50000
5   60000
6  100000

In [61]:
# Q58. Standardize column names.
# Hint:** `df.columns = df.columns.str.strip().str.lower().
# str.replace(" ", "_")` — clean all column names in one line.

data = {
    ' Full Name'      : ['Snehal', 'Komal', 'SK', 'Raj', 'Priya'],
    'Current Age'       : [23, 24, 25, 26, 27],
    ' Monthly Salary'    : [120000, 230000, 340000, 450000, 560000]}
df = pd.DataFrame(data)

df.columns = (df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_'))
print(df.columns)

Index(['full_name', 'current_age', 'monthly_salary'], dtype='object')

In [62]:
# Q59. Handle mixed data types in a column.
# Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.
# pd.to_numeric() converts values into numbers.
# Valid numbers → converted
# Invalid values → replaced with NaN

df = pd.DataFrame({
    'Age': ['20', '25', 'abc', '30']})

df['Age'] = pd.to_numeric(
    df['Age'],
    errors='coerce')
print(df)

    Age
0  20.0
1  25.0
2   NaN
3  30.0

In [63]:
# Q60. Remove special characters from text data.
# Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", 
# regex=True)` — use regex to keep only alphanumeric characters.

df = pd.DataFrame({
    'Text': [
        'John@123',
        'Alice#45',
        'Bob$99']})

df['Text'] = df['Text'].str.replace(
    r'[^ a-z A-Z 0-9 ]','',regex=True)
print(df)

      Text
0  John123
1  Alice45
2    Bob99

## 🔹 Section 4: Data Manipulation (Q61–Q80)

In [64]:
# Q61. Filter rows using AND condition.
# Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]`
#  — wrap each condition in parentheses and use `&`.

df = pd.DataFrame({
    'Name': ['Snehal', 'Komal', 'SK', 'Priya'],
    'Age': [22, 30, 28, 35],
    'Department': ['IT', 'HR', 'IT', 'Finance']})

result = df[
    (df['Age'] > 25) &
    (df['Department'] == 'IT')]
print(result)

  Name  Age Department
2   SK   28         IT

In [65]:
# Q62. Filter rows using OR condition.
# Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` 
# — use `|` between conditions.

result = df[
    (df['Age'] > 30) |
    (df['Department'] == 'HR')]
print(result)

    Name  Age Department
1  Komal   30         HR
3  Priya   35    Finance

In [66]:
# Q63. Filter rows using NOT condition.
# Hint:** `df[~(df["col"] == "val")]`
#  — use `~` to negate a boolean condition.

result = df[
    ~(df['Department'] == 'IT')]
print(result)

    Name  Age Department
1  Komal   30         HR
3  Priya   35    Finance

In [67]:
# Q64. Sort DataFrame by column values.
# Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

print(df.sort_values('Age'))

     Name  Age Department
0  Snehal   22         IT
2      SK   28         IT
1   Komal   30         HR
3   Priya   35    Finance

In [68]:
# Q65. Sort DataFrame by index.
# Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

df = pd.DataFrame({
    'Name': ['Snehal', 'Komal']
}, index=[2, 1])
print(df.sort_index())

     Name
1   Komal
2  Snehal

In [69]:
# Q66. Add calculated column.
# Hint:** `df["new"] = df["col1"] * df["col2"]` or
#  use `.assign(new=lambda x: ...)` for chainable operations.

df = pd.DataFrame({
    'Quantity': [2, 5, 3],
    'Price': [100, 200, 150]})

df['Total'] = df['Quantity'] * df['Price']
print(df)

   Quantity  Price  Total
0         2    100    200
1         5    200   1000
2         3    150    450

In [70]:
# Q67. Remove column using `drop()`.
# Hint:** `df.drop(columns=["col1","col2"])`. 
# Always use the `columns=` parameter to be explicit.

df = df.drop(columns=['Quantity'])
print(df)

   Price  Total
0    100    200
1    200   1000
2    150    450

In [71]:
# Q68. Remove rows using `drop()`.
# Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

df = df.drop(index=[2])
print(df)

   Price  Total
0    100    200
1    200   1000

In [72]:
# Q69. Use `map()` on a column.
# Hint:** `df["col"].map({"a": 1, "b": 2})` 
# substitutes values using a dict. Pass a function for element-wise transformation.

# Create a sample DataFrame
df = pd.DataFrame({
    'Size': ['S', 'M', 'L', 'S', 'M']
})

df['Size_Code'] = df['Size'].map({
    'S': 1,
    'M': 2,
    'L': 3
})
print(df)

df = pd.DataFrame({'Product' :['laptop','Phone','tAblet']})
df['Product'] = df['Product'].map(lambda x:  x.strip().lower())
print(df)

  Size  Size_Code
0    S          1
1    M          2
2    L          3
3    S          1
4    M          2
  Product
0  laptop
1   phone
2  tablet

In [73]:
# Q70. Apply function using `apply()`.
# Hint:** `df["col"].apply(func)` for a Series. 
# `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

df = pd.DataFrame({'Age': [20, 25, 30]})

df['Age_Plus_5'] = df['Age'].apply(
    lambda x: x + 5)      
print(df)

   Age  Age_Plus_5
0   20          25
1   25          30
2   30          35

In [74]:
# Q71. Apply element-wise using `applymap()` / `map()`.
# Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

df = pd.DataFrame({
    'A' : [1,2],
    'B' : [3,4]
})
result = df.applymap(lambda x: x * 10)
print(result)

    A   B
0  10  30
1  20  40

C:\Users\Snehal\AppData\Local\Temp\ipykernel_21600\3860116072.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  result = df.applymap(lambda x: x * 10)

In [75]:
# Q72. Chain multiple operations.
# Hint:** Use method chaining with `(df.copy().loc[...].
# sort_values(...)[cols].assign(...).reset_index(drop=True))`-resetting the index of a DataFrame
# — wrap in parentheses for multi-line readability.

df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [30, 22, 25],
    'Salary': [50000, 70000, 60000]
})

result = (
    df.copy()
    .sort_values('Salary')
    .assign(Bonus = lambda x: x['Salary'] * 0.10)
    .reset_index(drop= True)
)
print(result)

    Name  Age  Salary   Bonus
0   John   30   50000  5000.0
1    Bob   25   60000  6000.0
2  Alice   22   70000  7000.0

In [76]:
# Q73. Normalize numeric columns (Min-Max).
# Hint:(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())`
#  — result is in range [0, 1].

df = pd.DataFrame({
    'Age': [20, 30, 40, 50]})

df['Age_Normalized'] = (
    (df['Age'] - df['Age'].min()) /
    (df['Age'].max() - df['Age'].min())
)
print(df)

   Age  Age_Normalized
0   20        0.000000
1   30        0.333333
2   40        0.666667
3   50        1.000000

In [77]:
# Q74. Scale numerical data (Z-score standardization).
# Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

df = pd.DataFrame({
    'Age': [20, 30, 40, 50]})

df['Age_ZScore'] = (
    (df['Age'] - df['Age'].mean()) /
    df['Age'].std()
)
print(df)

   Age  Age_ZScore
0   20   -1.161895
1   30   -0.387298
2   40    0.387298
3   50    1.161895

In [78]:
# Q75. Rank values in a column.
# Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, 
# `method="dense"` to avoid gaps.

df = pd.DataFrame({
        'Marks' : [90, 75, 85, 95]
})
df['Rank'] = df['Marks'].rank(
    ascending=False)
print(df)

   Marks  Rank
0     90   2.0
1     75   4.0
2     85   3.0
3     95   1.0

In [79]:
# Q76. Create bins using `cut()`.
# Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

df = pd.DataFrame({
        'Marks' : [90, 75, 85, 95]
})

df['Category'] = pd.cut(    # Create equal width bins
    df['Marks'],           
    bins = 4
)
print(df)

   Marks       Category
0     90   (85.0, 90.0]
1     75  (74.98, 80.0]
2     85   (80.0, 85.0]
3     95   (90.0, 95.0]

In [80]:
# Q77. Create bins using `qcut()`.
# Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** 
# (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

df = pd.DataFrame({
        'Marks' : [90, 75, 85, 95, 67, 89, 76, 34]
})
df ['Quartile'] = pd.qcut(   # Create equal frequecy bins
    df['Marks'],
       q = 4
)
print(df)

# qcut(): each bin contain approximatly same number of observation

   Marks        Quartile
0     90   (89.25, 95.0]
1     75    (73.0, 80.5]
2     85   (80.5, 89.25]
3     95   (89.25, 95.0]
4     67  (33.999, 73.0]
5     89   (80.5, 89.25]
6     76    (73.0, 80.5]
7     34  (33.999, 73.0]

In [81]:
# Q78. Count unique values.
# Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()`
#  for frequency per unique value.

df = pd.DataFrame({
    'city' :['Mumbai','Delhi','Mumbai','Pune']
})
print(df['city'].nunique())

3

In [82]:
# Q79. Replace multiple values at once.
# Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a 
# list: `df.replace(["old1","old2"], "new")`.

df = pd.DataFrame({'City': ['Bombay','Madras','Delhi']})
df= df.replace({'city':{'Bombay' : 'Mumbai', 'Delhi' : 'Noida'}})
# df.replace(['Bombay', 'Madras'],'Indian City')
print(df)

     City
0  Bombay
1  Madras
2   Delhi

In [83]:
# Q80. Create flag column based on condition.
# Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` 
# — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

df = pd.DataFrame({
    'Salary':[30000, 50000, 80000]})

df['High_Salary'] = (df['Salary'] > 20000).astype(int)
print(df)

   Salary  High_Salary
0   30000            1
1   50000            1
2   80000            1

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

In [84]:
# Q81. Iterate over rows using `iterrows()`.
# Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.
# iterrows() loops through each row of the DataFrame.

df = pd.DataFrame({
    'Name' : ['Snehal', 'Komal', 'SK'],
    'Age' : [23, 24, 25]
})

for idx, row in df.iterrows():
    print(idx, row['Name'], row['Age'])

0 Snehal 23
1 Komal 24
2 SK 25

In [85]:
# Q82. Iterate using `itertuples()`.
# Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

df = pd.DataFrame({
    'Name' : ['Snehal', 'Komal', 'SK'],
    'Age' : [23, 24, 25]
})
for row in df.itertuples():
    print(row.Name, row.Age)

# itertuples() is a faster alternative to iterrows().
# Instead of returning Series objects, it returns named tuples, 
# which consume less memory and execute faster.

Snehal 23
Komal 24
SK 25

In [86]:
# Q83. Iterate over columns.
# Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

# for col in df.columns:
#     print(col)

for col_name, data in df.items(): #It returns (column_name, Series) pairs.
    print(col_name)
    print(data)

Name
0    Snehal
1     Komal
2        SK
Name: Name, dtype: object
Age
0    23
1    24
2    25
Name: Age, dtype: int64

In [87]:
# Q84. Avoid iteration using vectorization.
# Hint:** Replace `for` loops with direct column operations: 
# `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

result = []
for value in df['Age']:
    result.append(value * 2 + 1)
df['New Age'] = result
print(result)

[47, 49, 51]

In [88]:
# Q85. Group data using `groupby()`.
# Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

df = pd.DataFrame({
    'Department' : ['IT', 'IT', 'HR', 'HR'],
    'Salary' : [50000, 60000, 40000, 45000]
})
print(df.groupby('Department')['Salary'].mean())

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [89]:
# Q86. Calculate sum per group.
# Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

df.groupby('Department')['Salary'].sum()

Department
HR     85000
IT    110000
Name: Salary, dtype: int64

In [90]:
# Q87. Calculate multiple aggregations.
# Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 40000, 45000],
    'Bonus': [5000, 6000, 4000, 4500]
})

result = df.groupby('Department').agg({
    'Salary': 'mean',
    'Bonus': 'sum'
})

print(result)

             Salary  Bonus
Department
HR          42500.0   8500
IT          55000.0  11000

In [91]:
# Q88. Group by multiple columns.
# Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 40000, 45000],
    'Bonus': [5000, 6000, 4000, 4500],
    'Gender': ['M', 'F', 'F', 'M'],
})
Groupby =df.groupby(['Department', 'Gender'])['Salary'].mean()
print(Groupby)

Department  Gender
HR          F         40000.0
            M         45000.0
IT          F         60000.0
            M         50000.0
Name: Salary, dtype: float64

In [92]:
# Q89. Filter grouped data.
# Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.
# It keeps only groups that satisfy a condition.

result = df.groupby('Department').filter(lambda x: x['Salary'].mean() > 50000)
print(result)

  Department  Salary  Bonus Gender
0         IT   50000   5000      M
1         IT   60000   6000      F

In [ ]:
# Q90. Transform grouped data using `transform()`.
# Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.
# transform() : It returns group statistics while keeping the original DataFrame size unchanged.

df['Dept_Avg_Salary'] = (
    df.groupby('Department')['Salary']
      .transform('mean')
)
print(df)

  Department  Salary  Bonus Gender  Dept_Avg_Salary
0         IT   50000   5000      M          55000.0
1         IT   60000   6000      F          55000.0
2         HR   40000   4000      F          42500.0
3         HR   45000   4500      M          42500.0

In [ ]:
# Q91. Apply custom function in groupby.
# Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

result = df.groupby('Department')['Salary'].agg(
    lambda s: s.max() - s.min())
print(result)

Department
HR     5000
IT    10000
Name: Salary, dtype: int64

In [ ]:
# Q92. Create basic pivot table.
# Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

pivot = pd.pivot_table(df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='mean'
)
print(pivot)

In [95]:
# Q93. Use multiple aggregation functions in pivot.
# Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

pivot = pd.pivot_table(df,
    values='Salary',
    index='Department',
    aggfunc=['mean', 'max'])

print(pivot)

               mean    max
             Salary Salary
Department
HR          42500.0  45000
IT          55000.0  60000

In [96]:
# Q94. Handle missing values in pivot tables.
# Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

pivot = pd.pivot_table(df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='mean',
    fill_value=0
)
print(pivot)

Gender            F        M
Department
HR          40000.0  45000.0
IT          60000.0  50000.0

In [97]:
# Q95. Add margins (totals) in pivot tables.
# Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

pivot = pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='sum',
    margins=True,
    margins_name='TOTAL'
)
print(pivot)

Gender           F      M   TOTAL
Department
HR           40000  45000   85000
IT           60000  50000  110000
TOTAL       100000  95000  195000

In [98]:
# Q96. Create multi-level pivot table.
# Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

pivot = pd.pivot_table(
    df,
    values='Salary',
    index=['Department', 'Gender'],
    aggfunc='mean'
)

print(pivot)

                    Salary
Department Gender
HR         F       40000.0
           M       45000.0
IT         F       60000.0
           M       50000.0

In [99]:
# Q97. Convert DataFrame to pivot format.
# Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

result = df.pivot(
    index='Department',
    columns='Gender',
    values='Salary')
print(result)

Gender          F      M
Department
HR          40000  45000
IT          60000  50000

In [100]:
# Q98. Compare pivot vs groupby.
# Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

df.groupby('Department')['Salary'].mean()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [101]:
# Q99. Build summary report using pivot table.
# Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

report = pd.pivot_table(df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='sum',
    fill_value=0,
    margins=True
).round(2)
print(report)

Gender           F      M     All
Department
HR           40000  45000   85000
IT           60000  50000  110000
All         100000  95000  195000

In [111]:
# Q100. Create an end-to-end analysis workflow.
# Hint:** Follow this pipeline:  
# > 1. Load data →
#  2. Inspect (shape, dtypes, nulls) → 
#  3. Clean (fillna, drop_duplicates) →
#  4. Feature engineer → 
# 5. GroupBy/pivot analysis → 
# 6. Sort and rank → 
# 7. Export results.

# > 1. Load data →
import pandas as pd
df = pd.read_csv('E:\BRAINWORk\Python\python bw\Pandas\cars.csv')

#  2. Inspect (shape, dtypes, nulls) → 
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())
df = df.drop_duplicates()

#  3. Clean (fillna, drop_duplicates) →

numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

Shape: (8128, 5)

Columns:
Index(['brand', 'km_driven', 'fuel', 'owner', 'selling_price'], dtype='object')

Data Types:
brand            object
km_driven         int64
fuel             object
owner            object
selling_price     int64
dtype: object

Missing Values:
brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

<>:13: SyntaxWarning: invalid escape sequence '\B'
<>:13: SyntaxWarning: invalid escape sequence '\B'
C:\Users\Snehal\AppData\Local\Temp\ipykernel_21600\3929163337.py:13: SyntaxWarning: invalid escape sequence '\B'
  df = pd.read_csv('E:\BRAINWORk\Python\python bw\Pandas\cars.csv')